function out = videoparcellation(verts, faces, rois)

% faceAreas = calcFaceArea(verts, faces); 
% vertAreas = faces2verts(faces, faceAreas, height(verts)); 
% meanVert = (vertAreas' * verts)/sum(vertAreas); 

meanVert = mean(verts); 
meanParcel = splitapply0(@(x) mean(x,1), verts, rois); 

[az, el] = cart2sph(...
    meanParcel(:,1) - meanVert(:,1), ...
    meanParcel(:,2) - meanVert(:,2), ...
    meanParcel(:,3) - meanVert(:,3));
views = double(rad2deg([az+pi/2, el])); 

out = videofigs(max(rois), ...
    @(ii) patchvfc(verts, faces, (rois==ii)*ii, 'EdgeColor', [0.5 0.5 0.5]), ...
    @(ii) axis('image', 'on'), ...
    @(ii) view(views(ii,:)) , ...
    @(ii) clim([0, max(rois)])); 

end
